#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : qscintilla
Version  : 2.13.0
Release  : 223
URL      : https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.13.0/QScintilla_src-2.13.0.tar.gz
Source0  : https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.13.0/QScintilla_src-2.13.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: qscintilla-data = %{version}-%{release}
Requires: qscintilla-lib = %{version}-%{release}
BuildRequires : PyQt-builder
BuildRequires : PyQt5
BuildRequires : buildreq-kde
BuildRequires : buildreq-qmake
BuildRequires : pkgconfig(Qt5Designer)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5PrintSupport)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : sip

%description
QScintilla - Python Bindings for the QScintilla Programmers Editor Widget
=========================================================================

%package data
Summary: data components for the qscintilla package.
Group: Data

%description data
data components for the qscintilla package.


%package dev
Summary: dev components for the qscintilla package.
Group: Development
Requires: qscintilla-lib = %{version}-%{release}
Requires: qscintilla-data = %{version}-%{release}
Provides: qscintilla-devel = %{version}-%{release}
Requires: qscintilla = %{version}-%{release}

%description dev
dev components for the qscintilla package.


%package lib
Summary: lib components for the qscintilla package.
Group: Libraries
Requires: qscintilla-data = %{version}-%{release}

%description lib
lib components for the qscintilla package.


%prep
%setup -q -n QScintilla_src-2.13.0
cd %{_builddir}/QScintilla_src-2.13.0

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
export CXXFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export FCFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export FFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -Wl,--build-id=sha1"
export CFFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export LDFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -Wl,--build-id=sha1"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export LIBRARY_PATH="$LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export PATH="$PATH:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="$CPATH:/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_ALLOW_UNOFFICIAL_PROTOCOL=1
export __GL_SYNC_TO_VBLANK=0
export __GL_SYNC_DISPLAY_DEVICE=DFP-1
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DFP-1
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags1 end
pushd src
%qmake qscintilla.pro
test -r config.log && cat config.log
make  %{?_smp_mflags} V=1 VERBOSE=1
cd ../designer
%qmake
test -r config.log && cat config.log
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1625442325
rm -rf %{buildroot}
pushd src
%make_install
popd
## install_append content
#pushd Python
#cp pyproject-qt5.toml pyproject.toml
#sip-install
#popd
pushd designer
%make_install
popd
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qt5/qsci/api/python/Python-2.4.api
/usr/share/qt5/qsci/api/python/Python-2.5.api
/usr/share/qt5/qsci/api/python/Python-2.6.api
/usr/share/qt5/qsci/api/python/Python-2.7.api
/usr/share/qt5/qsci/api/python/Python-3.1.api
/usr/share/qt5/qsci/api/python/Python-3.2.api
/usr/share/qt5/qsci/api/python/Python-3.3.api
/usr/share/qt5/qsci/api/python/Python-3.4.api
/usr/share/qt5/qsci/api/python/Python-3.5.api
/usr/share/qt5/qsci/api/python/Python-3.6.api
/usr/share/qt5/qsci/api/python/Python-3.7.api
/usr/share/qt5/qsci/api/python/Python-3.8.api
/usr/share/qt5/qsci/api/python/Python-3.9.api
/usr/share/qt5/translations/qscintilla_cs.qm
/usr/share/qt5/translations/qscintilla_de.qm
/usr/share/qt5/translations/qscintilla_es.qm
/usr/share/qt5/translations/qscintilla_fr.qm
/usr/share/qt5/translations/qscintilla_pt_br.qm

%files dev
%defattr(-,root,root,-)
/usr/include/qt5/Qsci/qsciabstractapis.h
/usr/include/qt5/Qsci/qsciapis.h
/usr/include/qt5/Qsci/qscicommand.h
/usr/include/qt5/Qsci/qscicommandset.h
/usr/include/qt5/Qsci/qscidocument.h
/usr/include/qt5/Qsci/qsciglobal.h
/usr/include/qt5/Qsci/qscilexer.h
/usr/include/qt5/Qsci/qscilexeravs.h
/usr/include/qt5/Qsci/qscilexerbash.h
/usr/include/qt5/Qsci/qscilexerbatch.h
/usr/include/qt5/Qsci/qscilexercmake.h
/usr/include/qt5/Qsci/qscilexercoffeescript.h
/usr/include/qt5/Qsci/qscilexercpp.h
/usr/include/qt5/Qsci/qscilexercsharp.h
/usr/include/qt5/Qsci/qscilexercss.h
/usr/include/qt5/Qsci/qscilexercustom.h
/usr/include/qt5/Qsci/qscilexerd.h
/usr/include/qt5/Qsci/qscilexerdiff.h
/usr/include/qt5/Qsci/qscilexeredifact.h
/usr/include/qt5/Qsci/qscilexerfortran.h
/usr/include/qt5/Qsci/qscilexerfortran77.h
/usr/include/qt5/Qsci/qscilexerhtml.h
/usr/include/qt5/Qsci/qscilexeridl.h
/usr/include/qt5/Qsci/qscilexerjava.h
/usr/include/qt5/Qsci/qscilexerjavascript.h
/usr/include/qt5/Qsci/qscilexerjson.h
/usr/include/qt5/Qsci/qscilexerlua.h
/usr/include/qt5/Qsci/qscilexermakefile.h
/usr/include/qt5/Qsci/qscilexermarkdown.h
/usr/include/qt5/Qsci/qscilexermatlab.h
/usr/include/qt5/Qsci/qscilexeroctave.h
/usr/include/qt5/Qsci/qscilexerpascal.h
/usr/include/qt5/Qsci/qscilexerperl.h
/usr/include/qt5/Qsci/qscilexerpo.h
/usr/include/qt5/Qsci/qscilexerpostscript.h
/usr/include/qt5/Qsci/qscilexerpov.h
/usr/include/qt5/Qsci/qscilexerproperties.h
/usr/include/qt5/Qsci/qscilexerpython.h
/usr/include/qt5/Qsci/qscilexerruby.h
/usr/include/qt5/Qsci/qscilexerspice.h
/usr/include/qt5/Qsci/qscilexersql.h
/usr/include/qt5/Qsci/qscilexertcl.h
/usr/include/qt5/Qsci/qscilexertex.h
/usr/include/qt5/Qsci/qscilexerverilog.h
/usr/include/qt5/Qsci/qscilexervhdl.h
/usr/include/qt5/Qsci/qscilexerxml.h
/usr/include/qt5/Qsci/qscilexeryaml.h
/usr/include/qt5/Qsci/qscimacro.h
/usr/include/qt5/Qsci/qsciprinter.h
/usr/include/qt5/Qsci/qsciscintilla.h
/usr/include/qt5/Qsci/qsciscintillabase.h
/usr/include/qt5/Qsci/qscistyle.h
/usr/include/qt5/Qsci/qscistyledtext.h
/usr/lib64/libqscintilla2_qt5.so
/usr/lib64/qt5/mkspecs/features/qscintilla2.prf

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqscintilla2_qt5.so.15
/usr/lib64/libqscintilla2_qt5.so.15.1
/usr/lib64/libqscintilla2_qt5.so.15.1.0
/usr/lib64/qt5/plugins/designer/libqscintillaplugin.so
